Add voting feature
Puru12/alpha-ch pull request #8
Opened 2017-07-24 18:19 UTC by Puru12

can upvote (1) or downvote (0)

2017-07-24 19:40 UTC, congqiao requested changes

2017-07-24 19:40 UTC, congqiao commented on src/index.js
> +  app.put('/votes/:id', async (req,res)=>{
You are missing a space between `req` and `res`. You should run `yarn run format` and `yarn run lint` before committing.

2017-07-24 19:40 UTC, congqiao commented on src/index.js
> +    if (direction){
Use `switch`. This `else` includes everything except `0`, which is misleading.

2017-07-24 19:40 UTC, congqiao commented on src/index.js
> +    res.status(200).send({ postId: id.toHexString() })
The client already knows the post ID. Maybe return the whole post object. Also return 201 instead of 200.

2017-07-24 20:44 UTC, congqiao requested changes

2017-07-24 20:44 UTC, congqiao commented on src/index.js
> +    res.status(201).send({ postId: id })
The client already knows the post ID. Maybe return the whole post object.

2017-07-24 21:48 UTC, Puru12 commented on src/index.js
> +    res.status(201).send({ postId: id })
Sure.

2017-07-24 21:56 UTC, congqiao requested changes

2017-07-24 21:56 UTC, congqiao commented on src/index.js
> +    const postObject = await db.collection('posts').findOne({ _id: id })
Just name it `post`...

2017-07-25 02:18 UTC, congqiao approved these changes

2017-07-25 02:18 UTC, merged